# Generated by Django 3.2.4 on 2021-07-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(unique=True),
        ),
    ]
