# Generated by Django 3.2.4 on 2021-07-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_alter_entry_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='decimal',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(),
        ),
    ]
