# Generated by Django 3.2.4 on 2021-07-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20210723_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='decimal',
        ),
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=models.SlugField(default='name', max_length=10),
        ),
    ]
